use_frameworks!

platform :ios, '12.0'

target 'CommonUIKitComponents_Example' do
  pod 'CommonUIKitComponents', :path => '../'

  target 'CommonUIKitComponents_Tests' do
    inherit! :search_paths

    
  end
end
